### ISSUE TITLE
Codigo unico Cliente

### ISSUE THREAD

**Issue by kplian** [kplian/sis_ventas_farmacia#19]
Aumentar un codigo unico alfanumerico para Clientes, que servira para rastrear todos los pedidos realizados por el cliente. (Se podra utilizar en codigo QR)

**Comment by rensi4rn** [comment]
Este código deber ser autogenerado?

**Comment by rensi4rn** [comment]
se creo un triguer y una variable global para generación de código automáticos, el código de cliente figura en el recibo y a partir de el se genera el código QR
