### ISSUE TITLE
Modificar detalle en proceso WF

### ISSUE THREAD

**Issue by kplian** [kplian/sis_ventas_farmacia#20]
Aumentar dos columnas para el detalle, uno id_estado_wf y otro observaciones. Aumentar boton para edicion del detalle de la factura en el WF para poder modificar esos campos nuevos.

Esos campos nuevos se deberan mostrar en el tracking del pedido

**Comment by rensi4rn** [comment]
es muchas cosa id_estado _wf yo creo que tendría que ser un campo de texto abierto nada mas

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/20232630/fabb10b4-a83f-11e6-90cc-7a4e50e31b8b.png)

se aumenta una interface de detalle, desde donde se puede modifica los nuevos campos, estado, obs y serie
